import React, { useRef, useState } from 'react';
import { Check, X, Star, Zap, ChevronRight, Download, ArrowRight, TrendingUp } from 'lucide-react';
import html2pdf from 'html2pdf.js';

export default function ResumeReport({ analysis, onReset }) {
    const reportRef = useRef(null);
    const [isDownloading, setIsDownloading] = useState(false);

    if (!analysis) return null;

    const { score, summary, ats_feedback, magic_rewrites } = analysis;

    // Determine score color
    const getScoreColor = (s) => {
        if (s >= 80) return 'text-green-400 border-green-500 shadow-[0_0_30px_rgba(74,222,128,0.3)]';
        if (s >= 60) return 'text-yellow-400 border-yellow-500 shadow-[0_0_30px_rgba(250,204,21,0.3)]';
        return 'text-red-400 border-red-500 shadow-[0_0_30px_rgba(248,113,113,0.3)]';
    };

    const handleDownloadPDF = () => {
        setIsDownloading(true);
        const element = reportRef.current;
        const opt = {
            margin: [0.5, 0.5],
            filename: `Resume_Analysis_${score}.pdf`,
            image: { type: 'jpeg', quality: 0.98 },
            html2canvas: { scale: 2, useCORS: true, logging: false },
            jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
        };

        html2pdf().set(opt).from(element).save().then(() => {
            setIsDownloading(false);
        });
    };

    return (
        <div className="w-full max-w-6xl mx-auto px-4 py-8 animate-in fade-in slide-in-from-bottom-8 duration-700">

            {/* Top Navigation Bar */}
            <div className="flex justify-between items-center mb-8 bg-slate-900/50 backdrop-blur-md p-4 rounded-2xl border border-slate-700/50 sticky top-4 z-50 shadow-lg">
                <button
                    onClick={onReset}
                    className="text-slate-400 hover:text-white transition text-sm flex items-center gap-2 px-3 py-2 hover:bg-slate-800 rounded-lg"
                >
                    <ArrowRight className="rotate-180" size={16} /> Check Another Resume
                </button>

                <div className="flex items-center gap-3">
                    <button
                        onClick={handleDownloadPDF}
                        disabled={isDownloading}
                        className="flex items-center gap-2 px-5 py-2.5 bg-gradient-to-r from-blue-600 to-blue-500 hover:from-blue-500 hover:to-blue-400 text-white font-bold rounded-xl shadow-lg hover:shadow-blue-500/25 transition-all transform hover:-translate-y-0.5 disabled:opacity-70 disabled:cursor-wait"
                    >
                        {isDownloading ? (
                            <span className="animate-pulse">Generating PDF...</span>
                        ) : (
                            <>
                                <Download size={18} /> Download Report
                            </>
                        )}
                    </button>
                </div>
            </div>

            {/* Printable Area Wrapper */}
            <div ref={reportRef} className="bg-[#0f1623] p-4 md:p-10 rounded-3xl shadow-2xl border border-slate-800/60" id="report-content">

                {/* Header Section */}
                <div className="text-center mb-12 relative">
                    {/* Decorative background element for header */}
                    <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-64 h-64 bg-blue-500/10 rounded-full blur-3xl -z-10"></div>

                    <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-indigo-300 text-xs font-bold mb-4 uppercase tracking-wider">
                        <Star size={12} className="fill-indigo-300" /> AI Resume Audit
                    </div>
                    <h1 className="text-4xl md:text-5xl font-bold text-white mb-2 tracking-tight">Analysis Report</h1>
                    <p className="text-slate-400">Generated by InterVue AI Engine</p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-12">

                    {/* 1. Score Card (Hero) */}
                    <div className="md:col-span-1 bg-gradient-to-b from-slate-900 via-slate-900 to-slate-900/50 border border-slate-700/50 rounded-3xl p-8 flex flex-col items-center justify-center relative overflow-hidden group hover:border-slate-600 transition-all">
                        {/* Glow behind score */}
                        <div className={`absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-48 h-48 rounded-full blur-[80px] opacity-20 ${score >= 70 ? 'bg-green-500' : 'bg-red-500'} group-hover:opacity-30 transition-opacity`}></div>

                        <div className={`relative w-48 h-48 rounded-full border-[6px] flex items-center justify-center mb-6 ${getScoreColor(score)} bg-slate-950 transition-all duration-1000 transform group-hover:scale-105`}>
                            <div className="text-center">
                                <span className="text-6xl font-bold block text-white drop-shadow-lg">{score}</span>
                                <span className="text-xs uppercase tracking-[0.2em] text-slate-400 font-semibold">Match Score</span>
                            </div>
                        </div>
                        <div className="bg-slate-800/50 rounded-xl p-4 w-full">
                            <p className="text-center text-slate-300 text-sm leading-relaxed">
                                "{summary}"
                            </p>
                        </div>
                    </div>

                    {/* 2. ATS Check (List) */}
                    <div className="md:col-span-2 bg-slate-900/50 border border-slate-700/50 rounded-3xl p-8 flex flex-col justify-between hover:border-slate-600 transition-all">
                        <div>
                            <h3 className="text-xl font-bold text-white mb-6 flex items-center gap-2">
                                <TrendingUp className="text-blue-400" /> ATS Compliance Check
                            </h3>

                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-8">
                                {/* Missing Keywords */}
                                <div>
                                    <h4 className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-4 border-b border-slate-800 pb-2">Missing Keywords</h4>
                                    <div className="flex flex-wrap gap-2">
                                        {ats_feedback.missing_keywords && ats_feedback.missing_keywords.length > 0 ? (
                                            ats_feedback.missing_keywords.map((kw, i) => (
                                                <span key={i} className="px-3 py-1.5 bg-red-500/10 border border-red-500/20 text-red-300 rounded-lg text-sm flex items-center gap-1.5 font-medium">
                                                    <X size={14} strokeWidth={3} /> {kw}
                                                </span>
                                            ))
                                        ) : (
                                            <span className="px-4 py-2 bg-green-500/10 border border-green-500/20 text-green-400 rounded-lg text-sm flex items-center gap-2">
                                                <Check size={16} /> Perfect! All key skills detected.
                                            </span>
                                        )}
                                    </div>
                                    <p className="text-xs text-slate-500 mt-3 leading-relaxed">
                                        *Adding these keywords can increase your ATS ranking by up to 40%.
                                    </p>
                                </div>

                                {/* Formatting Issues */}
                                <div>
                                    <h4 className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-4 border-b border-slate-800 pb-2">Formatting Health</h4>
                                    {ats_feedback.formatting_issues && ats_feedback.formatting_issues.length > 0 ? (
                                        <ul className="space-y-3">
                                            {ats_feedback.formatting_issues.map((issue, i) => (
                                                <li key={i} className="text-sm text-slate-300 flex items-start gap-3 bg-slate-800/30 p-2 rounded-lg">
                                                    <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-yellow-500 shrink-0 shadow-[0_0_8px_rgba(234,179,8,0.5)]"></span>
                                                    {issue}
                                                </li>
                                            ))}
                                        </ul>
                                    ) : (
                                        <div className="flex items-center gap-3 text-green-400 bg-green-500/5 p-4 rounded-xl border border-green-500/10">
                                            <div className="p-2 bg-green-500/20 rounded-full">
                                                <Check size={16} />
                                            </div>
                                            <span className="font-medium text-sm">Resume layout is clean and parseable.</span>
                                        </div>
                                    )}
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

                {/* 3. Magic Rewrites */}
                <div className="relative">
                    <div className="absolute inset-0 bg-blue-500/5 blur-3xl -z-10 rounded-full"></div>
                    <h3 className="text-2xl font-bold text-white mb-8 flex items-center gap-3">
                        <div className="p-2 bg-yellow-500/10 rounded-lg border border-yellow-500/20">
                            <Zap className="text-yellow-400 fill-yellow-400" size={24} />
                        </div>
                        Magic Rewrites
                        <span className="text-sm font-normal text-slate-400 ml-auto hidden md:block">
                            AI-powered suggestions to boost impact
                        </span>
                    </h3>

                    <div className="grid grid-cols-1 gap-6">
                        {magic_rewrites.map((item, index) => (
                            <div key={index} className="bg-slate-900 border border-slate-700/50 rounded-2xl overflow-hidden hover:border-blue-500/40 transition-all duration-300 shadow-lg group">
                                {/* Header */}
                                <div className="px-6 py-3 bg-slate-800/50 border-b border-slate-700/50 flex justify-between items-center">
                                    <span className="text-xs font-bold text-slate-500 uppercase tracking-wider">Bullet Point Analysis #{index + 1}</span>
                                </div>

                                <div className="grid grid-cols-1 md:grid-cols-2">
                                    {/* Before */}
                                    <div className="p-6 border-b md:border-b-0 md:border-r border-slate-700/50 bg-red-500/5">
                                        <div className="flex items-center gap-2 mb-3">
                                            <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-red-500/20 text-red-300 uppercase">Original</span>
                                        </div>
                                        <p className="text-slate-300 text-sm md:text-base opacity-80 group-hover:opacity-100 transition-opacity">
                                            "{item.original}"
                                        </p>
                                    </div>

                                    {/* After */}
                                    <div className="p-6 bg-gradient-to-br from-green-500/5 to-blue-600/5 relative overflow-hidden">
                                        <div className="absolute top-0 right-0 p-4 opacity-10">
                                            <Star size={40} className="text-white" />
                                        </div>
                                        <div className="flex items-center gap-2 mb-3">
                                            <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-green-500/20 text-green-300 uppercase flex items-center gap-1">
                                                <Zap size={10} className="fill-green-300" /> AI Rewritten
                                            </span>
                                        </div>
                                        <p className="text-white font-medium text-sm md:text-base leading-relaxed mb-4">
                                            "{item.rewritten}"
                                        </p>
                                        <div className="flex items-start gap-2 text-xs text-blue-300 bg-blue-500/10 p-3 rounded-lg border border-blue-500/20">
                                            <Star size={14} className="mt-0.5 shrink-0" />
                                            <span><span className="font-bold">Why it works:</span> {item.explanation}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>

                <div className="mt-12 text-center">
                    <p className="text-slate-500 text-xs">
                        InterVue AI • Generated on {new Date().toLocaleDateString()}
                    </p>
                </div>
            </div>

        </div>
    );
}
